apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${name}
spec:
  version: 8.6.1
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: master
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  - name: data
    count: 1
    config:
      node.roles: ["data", "ingest", "ml", "transform"]
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false