name: "IaC-Automation"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
      id-token: write
      contents: read

env:
  TFLINT_CONFIG: config/tflint.hcl
  REGION_VAR_FILE: "envs/dev/us-east-1/terraform.tfvars"
  GLOBAL_VAR_FILE: "envs/dev/global/terraform.tfvars"
  BACKEND_CONFIG: "envs/dev/us-east-1/backend.tfvars"
  PLAN_BIN: plan.bin
  PLAN_JSON: plan.json
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }} 
jobs:
  iac_automation:
    name: "Rails IaC"
    runs-on: ubuntu-latest
    container: ghcr.io/rameshcreations/iac-image:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::592309593815:role/rails-aws-master-github-oidc
          role-session-name: rails-github-ci
          aws-region: us-east-1
          
      - name: Check AWS Creds
        run: aws sts get-caller-identity

      - name: Check Tools Versions
        run: |
          aws --version
          terraform --version
          tflint --version
          infracost --version
          driftctl version
          tfsec --version

      - name: Terraform Init+Fmt+Validate
        run: |
          echo "==========================="
          echo "ℹ️  terraform init+fmt+validate"
          echo "==========================="
          terraform init -backend=false
          terraform fmt -recursive -write=false
          terraform validate

      - name: Terraform tflint
        run: |
          echo "==========================="
          echo "ℹ️  terraform tflint"
          echo "==========================="
          tflint --init --config=${TFLINT_CONFIG} --var-file=${REGION_VAR_FILE} --var-file=${GLOBAL_VAR_FILE} .
          tflint --config=${TFLINT_CONFIG} --format=junit --force --var-file=${REGION_VAR_FILE} --var-file=${GLOBAL_VAR_FILE} . > tflint.xml
          tflint --config=${TFLINT_CONFIG} --force --var-file=${REGION_VAR_FILE} --var-file=${GLOBAL_VAR_FILE} .

      - name: Terraform Plan
        run: |   
          echo "==========================="
          echo "ℹ️  plan"
          echo "==========================="
          terraform init -backend-config=${BACKEND_CONFIG}
          terraform plan -var-file=${REGION_VAR_FILE} -var-file=${GLOBAL_VAR_FILE} -out=$PLAN_BIN
          terraform show -json $PLAN_BIN > $PLAN_JSON

      - name: Cost Calculator
        run: |   
          echo "==========================="
          echo "ℹ️  infracost"
          echo "==========================="
          infracost configure set enable_dashboard true
          infracost breakdown --path $PLAN_JSON --terraform-plan-flags "-var-file=$REGION_VAR_FILE "-var-file=$GLOBAL_VAR_FILE""

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: |
            tflint.xml
            terraform-plan.json
    