name: "IaC-Automation"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  iac_automation:
    name: "Rails IaC"
    runs-on: ubuntu-latest
    container: ghcr.io/rameshcreations/iac-image:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Versions
        run: |
          terraform --version
          tflint --version
          infracost --version
          driftctl version
          tfsec --version
      