name: "IaC-Automation"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  iac_automation:
    name: "Rails IaC"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::592309593815:role/rails-aws-master-github-oidc
          role-duration-seconds: 600
          aws-region: us-east-1
          
      - name: Check AWS Creds
        run: aws sts get-caller-identity